name = "blog"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
"pages_build_output_dir": ".vercel/output/static"

[env.production.vars]
SPOTIFY_CLIENT_ID="47b5b2ae756f416d99bc3185a9702817"
SPOTIFY_CLIENT_SECRET="006860289e1c45dd9c95997b3d39feff"
SPOTIFY_REFRESH_TOKEN="AQDfZMDsssDwOqpt94YaX4lZ0WD_W8H4fraQPQjP9zuJgGY6UmWKtBU1fZCWK7XC7GVSnjYu5QQ_sGI7Hy2kGsb2NhkoIJqWV1bWgS-rb7GOwahBgGEfyEjLylbUJNMOw-Y"

DATABASE_URL="postgres://neondb_owner:npg_RXOSyrguN5s6@ep-shy-smoke-a5peybwr-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"

NEXT_PUBLIC_GISCUS_REPO="WangJinxi0518/blog"
NEXT_PUBLIC_GISCUS_REPOSITORY_ID="R_kgDOOfjHig"
NEXT_PUBLIC_GISCUS_CATEGORY="General"
NEXT_PUBLIC_GISCUS_CATEGORY_ID="DIC_kwDOOfjHis4CpfC_"
NEXT_PUBLIC_UTTERANCES_REPO="WangJinxi0518/blog"

NEXT_UMAMI_ID="8ce6c07c-4c89-4d2b-ab21-6b07abae878f"

BUTTONDOWN_API_KEY="f71af58a-8989-4a4b-ab47-79fcd6c9dd48"

